apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-server
  template:
    metadata:
      labels:
        app: mlflow-server
    spec:
      containers:
        - name: mlflow
          image: custom-mlflow:5.5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: BACKEND_STORE_URI
              value: "postgresql://mlflow_user:$(POSTGRES_PASSWORD)@postgres:5432/mlflow" # $(POSTGRES_PASSWORD) will be replaced at runtime by the script
            - name: DEFAULT_ARTIFACT_ROOT
              value: "file:///tmp/mlflow"
          volumeMounts:
            - name: mlflow-storage
              mountPath: /tmp/mlflow
      volumes:
        - name: mlflow-storage
          hostPath:
            path: /tmp
            type: Directory
