apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-server
  template:
    metadata:
      labels:
        app: mlflow-server
    spec:
      containers:
        - name: mlflow
          image: custom-mlflow:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: BACKEND_STORE_URI
              value: postgresql://<username>:<password>@<postgres-service-name>:5432/mlflow
            - name: DEFAULT_ARTIFACT_ROOT
              value: file:///mnt/mlflow
          volumeMounts:
            - name: mlflow-storage
              mountPath: /mnt/mlflow

      volumes:
        - name: mlflow-storage
          hostPath:
            path: /Users/ved/mlflow
            type: Directory
